### ISSUE TITLE
Cross-referencing other information

### ISSUE THREAD

**Issue by DonaldTsang** [shaoxiongji/awesome-knowledge-graph#2]
Please take a look at https://github.com/husthuke/awesome-knowledge-graph and see if there are missing papers that can be added to this repo.

**Comment by shaoxiongji** [comment]
Thanks. A link to this repo added. Maybe have a look later.

**Comment by DonaldTsang** [comment]
@shaoxiongji I am referring to the papers, tools and repos within that link that can be added to this repo, but that is good to know as well.
