### ISSUE TITLE
make this an "awesome list"

### ISSUE THREAD

**Issue by VladimirAlexiev** [shaoxiongji/awesome-knowledge-graph#9]
An "awesome list" is a marketing way to let more people find this excellent resource
- rename repo to `awesome-knowledge-graphs`
- add tag `awesome-list` so it shows up in https://github.com/topics/awesome-list
- read https://github.com/sindresorhus/awesome/blob/main/awesome.md and add one of the badges (little images)
- add your list to https://github.com/sindresorhus/awesome by following these guidelines: https://github.com/sindresorhus/awesome/blob/main/contributing.md
  - you may also read https://github.com/sindresorhus/awesome/blob/main/create-list.md
  - it addition to github, it will then show up on https://awesomelists.top, see an example: https://awesomelists.top/#repos/onurakpolat/awesome-bigdata
- add your list to https://github.com/semantalytics/awesome-semantic-web

THANKS!

**Comment by VladimirAlexiev** [comment]
Also run https://github.com/sindresorhus/awesome-lint, which will suggest edits to make your content most useful in https://awesomelists.top/

**Comment by shaoxiongji** [comment]
Thanks for your suggestion. No plan to make these changes.
